_common: !include "../shared.yaml"

name: environment-core
<<: *common

dependencies:
  - base

library:
  source-dirs:
    - src
  dependencies:
    - adjunctions
    - comonad
    - base
  <<: *library

tests:
  environment-core-test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - environment-core
    <<: *test
