_common: !include "../shared.yaml"

name: scripts
<<: *common

dependencies:
  - base

tests:
  scripts-test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - scripts
    <<: *test

executables:
  edit-script:
    main: edit-script.hs
    source-dirs: src
    dependencies:
      - text
      - process
      - directory
      - base
      - commander
    <<: *executable
  new-script:
    main: new-script.hs
    source-dirs: src
    dependencies:
      - text
      - commander
      - process
      - directory
