_common: !include "../shared.yaml"

name: scripts
<<: *common

dependencies:
  - base

executables:
  edit-script:
    main: edit-script.hs
    source-dirs: src
    dependencies:
      - text
      - process
      - directory
      - base
      - commander
    <<: *executable
  new-script:
    main: new-script.hs
    source-dirs: src
    dependencies:
      - text
      - commander
      - process
      - directory
  new-project:
    main: new-project.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  soviet:
    main: soviet.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  wow:
    main: wow.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  fart:
    main: fart.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  bad:
    main: bad.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  good:
    main: good.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  sound:
    main: sound.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  list-scripts:
    main: list-scripts.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
