_common: !include "../shared.yaml"

name: scripts
<<: *common

dependencies:
  - base

executables:
  edit-script:
    main: edit-script.hs
    source-dirs: src
    dependencies:
      - text
      - process
      - directory
      - base
      - commander
    <<: *executable
  new-script:
    main: new-script.hs
    source-dirs: src
    dependencies:
      - text
      - commander
      - process
      - directory
  new-project:
    main: new-project.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
  list-scripts:
    main: list-scripts.hs
    source-dirs: src
    dependencies:
      - base
      - commander
      - process
      - directory
      - text
      - bytestring
    <<: *executable
